image:
  repository: 172.17.0.2:5000/ai-notification/event-service
  tag: "fdf7fc54"

healthGrpcPort: 50054
appGrpcPort: 50154
appGrpcPortEnvName: EVENT_GRPC_PORT

database:
  enabled: true
  name: event_db
