image:
  repository: 172.17.0.2:5000/ai-notification/notification-service
  tag: "fdf7fc54"

healthGrpcPort: 50057
appGrpcPort: 50157
appGrpcPortEnvName: NOTIFICATION_GRPC_PORT

database:
  enabled: true
  name: notification_db
