image:
  repository: 172.30.0.20:5000/ai-notification/analytics-service
  tag: "70980d08"

healthGrpcPort: 50060
appGrpcPort: 50160
appGrpcPortEnvName: ANALYTICS_GRPC_PORT

database:
  schemaHash: "2e557e57a3a0"
  enabled: true
  name: analytics_db
