image:
  repository: 172.17.0.3:5000/ai-notification/notification-service
  tag: "0d1c08b3"

healthGrpcPort: 50057
appGrpcPort: 50157
appGrpcPortEnvName: NOTIFICATION_GRPC_PORT

database:
  enabled: true
  name: notification_db
