image:
  repository: 172.17.0.2:5000/ai-notification/identity-service
  tag: "fdf7fc54"

healthGrpcPort: 50052
appGrpcPort: 50152
appGrpcPortEnvName: AUTH_GRPC_PORT

database:
  enabled: true
  name: identity_db
