image:
  repository: 172.17.0.2:5000/ai-notification/analytics-service
  tag: "fdf7fc54"

healthGrpcPort: 50060
appGrpcPort: 50160
appGrpcPortEnvName: ANALYTICS_GRPC_PORT

database:
  enabled: true
  name: analytics_db
