image:
  repository: 172.17.0.3:5000/ai-notification/template-service
  tag: "fdf7fc54"

healthGrpcPort: 50059
appGrpcPort: 50159
appGrpcPortEnvName: TEMPLATE_GRPC_PORT

database:
  enabled: true
  name: template_db
