image:
  repository: 172.17.0.3:5000/ai-notification/analytics-service
  tag: "0d1c08b3"

healthGrpcPort: 50060
appGrpcPort: 50160
appGrpcPortEnvName: ANALYTICS_GRPC_PORT

database:
  schemaHash: "initial"
  enabled: true
  name: analytics_db
