image:
  repository: 172.30.0.20:5000/ai-notification/identity-service
  tag: "70980d08"

healthGrpcPort: 50052
appGrpcPort: 50152
appGrpcPortEnvName: AUTH_GRPC_PORT

database:
  schemaHash: "df8a743817a3"
  enabled: true
  name: identity_db
