image:
  repository: 172.17.0.3:5000/ai-notification/audit-service
  tag: "0d1c08b3"

healthGrpcPort: 50061
appGrpcPort: 50161
appGrpcPortEnvName: AUDIT_GRPC_PORT

database:
  schemaHash: "initial"
  enabled: true
  name: audit_db
