image:
  repository: 172.17.0.2:5000/ai-notification/rule-engine-service
  tag: "fdf7fc54"

healthGrpcPort: 50056
appGrpcPort: 50156
appGrpcPortEnvName: RULE_ENGINE_GRPC_PORT

database:
  enabled: true
  name: rule_engine_db
