image:
  repository: 172.30.0.20:5000/ai-notification/rule-engine-service
  tag: "70980d08"

healthGrpcPort: 50056
appGrpcPort: 50156
appGrpcPortEnvName: RULE_ENGINE_GRPC_PORT

database:
  schemaHash: "9d3450791f43"
  enabled: true
  name: rule_engine_db
