image:
  repository: 172.30.0.20:5000/ai-notification/template-service
  tag: "70980d08"

healthGrpcPort: 50059
appGrpcPort: 50159
appGrpcPortEnvName: TEMPLATE_GRPC_PORT

database:
  schemaHash: "001646d7dee5"
  enabled: true
  name: template_db
