image:
  repository: 172.17.0.2:5000/ai-notification/tenant-service
  tag: "fdf7fc54"

healthGrpcPort: 50053
appGrpcPort: 50153
appGrpcPortEnvName: TENANT_GRPC_PORT

database:
  enabled: true
  name: tenant_db
