image:
  repository: 172.30.0.20:5000/ai-notification/audit-service
  tag: "70980d08"

healthGrpcPort: 50061
appGrpcPort: 50161
appGrpcPortEnvName: AUDIT_GRPC_PORT

database:
  schemaHash: "fc0a4b010b3a"
  enabled: true
  name: audit_db
