image:
  repository: 172.17.0.3:5000/ai-notification/event-service
  tag: "0d1c08b3"

healthGrpcPort: 50054
appGrpcPort: 50154
appGrpcPortEnvName: EVENT_GRPC_PORT

database:
  enabled: true
  name: event_db
