image:
  repository: 172.17.0.3:5000/ai-notification/identity-service
  tag: "0d1c08b3"

healthGrpcPort: 50052
appGrpcPort: 50152
appGrpcPortEnvName: AUTH_GRPC_PORT

database:
  enabled: true
  name: identity_db
