apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "nest-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    {{- if .Values.httpPort }}
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: http
      {{- if .Values.httpNodePort }}
      nodePort: {{ .Values.httpNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.appGrpcPort }}
    - name: grpc
      port: {{ .Values.appGrpcPort }}
      targetPort: grpc
    {{- end }}
    - name: health
      port: {{ .Values.healthGrpcPort }}
      targetPort: health
