image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1
port: 8011
grpcHealthPort: 50062

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
